### ISSUE TITLE
system-ghc and install-ghc in stack.yaml

### ISSUE THREAD

**Issue by cdepillabout** [notogawa/haiji#1]
Why is `system-ghc` set to `false` and `install-ghc` set to `true` in the `stack.yaml` file?

As an end-user (who wants to play around with `haiji`), when doing `stack build` I was surprised that `stack` started to download `ghc` even though I already have it installed on my system through the system package manager.

**Comment by notogawa** [comment]
The reason is http://notogawa.hatenablog.com/entry/2015/12/02/000544

**Comment by cdepillabout** [comment]
Okay, that makes sense.  Thanks for the explanation.
