### ISSUE TITLE
helper function for use with ghc-8's visible type application

### ISSUE THREAD

**Issue by cdepillabout** [notogawa/haiji#4]
It would be nice to have a function to easily create template parameters with ghc-8's visible type application.

I'm thinking it would work like this:

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
module Main where

import Data.Default (def)
import Text.Haiji 
import qualified Data.Text as T
import qualified Data.Text.Lazy as LT
import qualified Data.Text.Lazy.IO as LT

main :: IO ()
main = LT.putStr $ render $(haijiFile def "content3.tmpl") $
           Key @"a_variable" ..= ("hello" :: LT.Text) `merge`
           Key @"b_variable" ..= ("world" :: LT.Text) `merge`
           Key @"c_variable" ..= ("hogehoge" :: LT.Text)
```
This would get rid of the need for using the `key` quasiquoter.  However, it would only work on ghc-8.

The `(..=)` function would just be `flip singleton` (in `Text.Haiji.Dictionary`).

**Comment by cdepillabout** [comment]
Ideally, it would be nice to be able to do something like this:

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
module Main where

import Data.Default (def)
import Text.Haiji 
import qualified Data.Text as T
import qualified Data.Text.Lazy as LT
import qualified Data.Text.Lazy.IO as LT

main :: IO ()
main = LT.putStr $ render $(haijiFile def "content3.tmpl") $
           toDict @"a_variable" ("hello" :: LT.Text) `merge`
           toDict @"b_variable" ("world" :: LT.Text)
```

However, I couldn't figure out a way to get visible type application to work like this.

**Comment by notogawa** [comment]
Like this ?
~~~~
toDict :: forall k x . x -> Dict '[ k :-> x ]
toDict = flip singleton Key
~~~~

**Comment by cdepillabout** [comment]
> Like this ?
>
> ```haskell
> toDict :: forall k x . x -> Dict '[ k :-> x ]
> toDict = flip singleton Key
> ```

Yeah, that's the function I was trying, but I couldn't get the visible type application to work with it.  I kept getting a compiler error that said ghc couldn't figure out what `k` should be.

I don't know enough about the (limitations of) visible type application to figure out what the problem is.

**Comment by notogawa** [comment]
This `toDict` definition works for me. Do you write `forall k x` ?

**Comment by notogawa** [comment]
Try [haiji-0.2.0.0](https://hackage.haskell.org/package/haiji-0.2.0.0).

**Comment by cdepillabout** [comment]
@notogawa Well, this is embarassing, but now the `toDict` function works for me too!  I'm not sure what I was doing wrong originally.

However, it works well now!  Pretty much exactly what I was looking for.  Thanks!
